### ISSUE TITLE
Problem with the arrow2 v0.14 dependency

### ISSUE THREAD

**Issue by GhisF** [natir/vcf2parquet#1]
Hi,

I got on some large vcf file the following an error message and a corrupted parquet file.

The error :
```Error: Lib { error: Arrow(ExternalFormat("File out of specification: min value of a page is required")) }```

It is a problem coming from the arrow2 dependency and it is fixed in the version 0.15 ([see the issue report](https://github.com/jorgecarleitao/arrow2/issues/1146)).

After updating the dependency and some very minor changes in the code I was able to convert my files.

Thanks for this tools.

**Comment by natir** [comment]
I hope my patch solve your issue. If it's not the case feel free to reopen this issue and send example data if you can.
